[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[server]
headless = true
port = 8501
maxUploadSize = 1000
maxMessageSize = 1000
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
allowRunOnSave = true

[browser]
gatherUsageStats = false
